### ISSUE TITLE
iBeacon stops immediately after start

### ISSUE THREAD

**Issue by romanpeters** [pstreule/hassio-addons#1]
I can't get this add-on to work.
Every time I start it, it immediately stops by itself.
I'm running Hass.io 0.68.1 on a Raspberry Pi 3, with the bluetooth add-on installed.

These are the logs I'm receiving from the add-on:
```starting version 3.2.4
Stop advertising:
hcitool -i hci0 cmd 0x08 0x000A 00
< HCI Command: ogf 0x08, ocf 0x000a, plen 1
  00 
> HCI Event: 0x0e plen 4
  01 0A 20 00 
Set advertising parameters:
hcitool -i hci0 cmd 0x08 0x0006 a0 00 a0 00 03 00 00 00 00 00 00 00 00 07 00
< HCI Command: ogf 0x08, ocf 0x0006, plen 15
  A0 00 A0 00 03 00 00 00 00 00 00 00 00 07 00 
> HCI Event: 0x0e plen 4
  01 06 20 00 
Start advertising:
hcitool -i hci0 cmd 0x08 0x000A 01
< HCI Command: ogf 0x08, ocf 0x000a, plen 1
  01 
> HCI Event: 0x0e plen 4
  01 0A 20 00 
Set iBeacon advertisement data:
hcitool -i hci0 cmd 0x08 0x0008 1e 02 01 06 1a ff 4c 00 02 15 63 C1 7A DC 7B 80 45 D2 82 12 54 13 67 B0 70 81 00 00 00 00 c4 00
< HCI Command: ogf 0x08, ocf 0x0008, plen 32
  1E 02 01 06 1A FF 4C 00 02 15 63 C1 7A DC 7B 80 45 D2 82 12 
  54 13 67 B0 70 81 00 00 00 00 C4 00 
> HCI Event: 0x0e plen 4
  01 08 20 00 
iBeacon mode enabled. Presence UUID: 63C17ADC-7B80-45D2-8212-541367B07081```

**Comment by pstreule** [comment]
The add-on doesn't need to keep running. It just configures the Bluetooth chip to advertise as a beacon, so it only needs to be run once.
The log output looks like that was successful, so you should see your Raspberry pi advertise as a beacon with the UUID `63C17ADC-7B80-45D2-8212-541367B07081`.

**Comment by romanpeters** [comment]
Ah, I see. For some reason it wasn't showing up in the app on my phone, but I tried it again today and it does seem to work. Thanks!
